dist: bionic

language: c

notifications:
 - email: true

before_script:
 # Download the kernel
 - sudo apt-get install libelf-dev wget tar gzip python
 - wget https://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.1.52.tar.gz
 - tar xf linux-4.1.52.tar.gz
 - mv linux-4.1.52 linux-stable
 - ./.travis_get_mainline_kernel

script:
 # Copy cifsd source to kernel
 - mv linux-stable ../
 - mv linux ../
 - mkdir ../linux-stable/fs/cifsd
 - cp -ar * ../linux-stable/fs/cifsd/
 - mkdir ../linux/fs/cifsd
 - cp -ar * ../linux/fs/cifsd/

 # Compile with 4.1 kernel
 - cd ../linux-stable
 - yes "" | make oldconfig
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo 'CONFIG_CIFS_INSECURE_SERVER=y' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile with latest Tovalds' kernel
 - cd ../linux
 - yes "" | make oldconfig
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo 'CONFIG_CIFS_INSECURE_SERVER=y' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile secure server build (no smb1.0 & smb2.0) with 4.1 kernel
 - cd ../linux-stable
 - yes "" | make oldconfig
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo '# CONFIG_CIFS_INSECURE_SERVER is not set' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko

 # Compile secure server build (no smb1.0 & smb2.0) with latest Tovalds' kernel
 - cd ../linux
 - yes "" | make oldconfig
 - echo 'obj-$(CONFIG_CIFS_SERVER) += cifsd/' >> fs/Makefile
 - echo 'source "fs/cifsd/Kconfig"' >> fs/Kconfig
 - echo 'CONFIG_CIFS_SERVER=m' >> .config
 - echo '# CONFIG_CIFS_INSECURE_SERVER is not set' >> .config
 - gcc -v
 - make fs/cifsd/cifsd.ko
